### ISSUE TITLE
Scheduling of the two Introduction sessions

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/2020-unavco-course#1]
Here is my plan for the <1-hour-long introduction to the workshop session.  It will be run as a webinar since it is mostly for information and touch base, and we may have ~100 people attending each one.  I am expecting we run two sessions: One optimized for the US mainland attendees, and one for the European and Far East attendees.  Everybody would get zoom invitations to both and can attend both or none.  As for timing see graphs below:

### June 30, 2020 Introduction [10 am HST (GMT-10)]

![tzmap1](https://user-images.githubusercontent.com/26473567/85958725-4d535900-b933-11ea-9b04-70aaa2eb4005.png)

This session would start leisurely at 10 am Hawaii time.  This should make it possible for @btozer to attend as well.  So all developers and helpers should be able to attend and say hi and say a few things about your self (30- secs?). **Note**: Light green bars are Group 1 people (those who will be in the breakout rooms and get hands-on help during the actual workshop), while light red are Group 2 (who only will have access to the lectures).  Darker green means overlap.  Total about 150 attendees.

July 1, 2020 Introduction [9 am UTC (GMT-0)]

![tzmap2](https://user-images.githubusercontent.com/26473567/85958750-868bc900-b933-11ea-84ef-59737d8a738e.png)

This is as late as I can reasonably handle (I am old).  So starts 11 pm Hawaii time for a morning session in Europe, and afternoon further east.  Mainland US would sleep here as would @seisman and Eric.

During the session, which I imagine I will be running, the rest of you can handle the Chat room and answer questions posted there.  It is too many to deal with verbally I think but if there is a large number of no-shows then perhaps we can improvise.  So, unless there are stern objections to this plan, I will schedule the two zoom sessions using my UH zoom account and send both invitations to all registered attendees plus the 7 instructors, plus cc to Sandwell.  I expect to do all this on Monday morning at the very very latest, ideally tonight Sunday in Hawaii.  Especially, if any of the core folks have objections, please voice them now, @GenericMappingTools/core.

Sorry for largely ignoring our contributers in this, it is a rush job as always.  If any of you wish to attend, and possibly help down the road (the main 2-day workshop is on July 20-21) then please let me know, @GenericMappingTools/gmt-contributors.

Let me know if you think these sessions should be recorded.  I guess they should.  I am thinking this experiment might turn out to be very helpful for us to design future workshops fully online, including for developer-wannabees.

**Comment by PaulWessel** [comment]
I wonder if we should try to have UNAVCO (Melissa) actually set up and run the zooms and be responsible for the recording and posting of them? One less thing for me/us to organize.

**Comment by anbj** [comment]
I dont think I will be able to contribute, but I would really like to follow this (either live or later). What is the best way to do that? Recordings, course material?

**Comment by WalterHFSmith** [comment]
I do think they should be recorded.
If you are using Zoom there is a feature to send it straight to YouTube also, with a live-stream there, after which it is available on your YouTube channel to be watched at any time.

W

**Comment by PaulWessel** [comment]
Thanks Walter.  Will be recorded.  Sorry we need to use zoom on this so I
did not send you an invite to the zoom introductions tomorrow.  let me know
if/when that policy has changed or will change.

On June 29, 2020 at 4:22:46 AM, Walter H F Smith (notifications@github.com)
wrote:

I do think they should be recorded.
If you are using Zoom there is a feature to send it straight to YouTube
also, with a live-stream there, after which it is available on your YouTube
channel to be watched at any time.

W

> On Jun 28, 2020, at 5:48 PM, Paul Wessel <notifications@github.com> wrote:
>
>
> Here is my plan for the <1-hour-long introduction to the workshop
session. It will be run as a webinar since it is mostly for information and
touch base, and we may have ~100 people attending each one. I am expecting
we run two sessions: One optimized for the US mainland attendees, and one
for the European and Far East attendees. Everybody would get zoom
invitations to both and can attend both or none. As for timing see graphs
below:
>
> June 30, 2020 Introduction [10 am HST (GMT-10)]
>
>
>
> This session would start leisurely at 10 am Hawaii time. This should make
it possible for @btozer to attend as well. So all developers and helpers
should be able to attend and say hi and say a few things about your self
(30- secs?). Note: Light green bars are Group 1 people (those who will be
in the breakout rooms and get hands-on help during the actual workshop),
while light red are Group 2 (who only will have access to the lectures).
Darker green means overlap. Total about 150 attendees.
>
> July 1, 2020 Introduction [9 am UTC (GMT-0)]
>
>
>
> This is as late as I can reasonably handle (I am old). So starts 11 pm
Hawaii time for a morning session in Europe, and afternoon further east.
Mainland US would sleep here as would @seisman and Eric.
>
> During the session, which I imagine I will be running, the rest of you
can handle the Chat room and answer questions posted there. It is too many
to deal with verbally I think but if there is a large number of no-shows
then perhaps we can improvise. So, unless there are stern objections to
this plan, I will schedule the two zoom sessions using my UH zoom account
and send both invitations to all registered attendees plus the 7
instructors, plus cc to Sandwell. I expect to do all this on Monday morning
at the very very latest, ideally tonight Sunday in Hawaii. Especially, if
any of the core folks have objections, please voice them now,
@GenericMappingTools/core.
>
> Sorry for largely ignoring our contributers in this, it is a rush job as
always. If any of you wish to attend, and possibly help down the road (the
main 2-day workshop is on July 20-21) then please let me know,
@GenericMappingTools/gmt-contributors.
>
> Let me know if you think these sessions should be recorded. I guess they
should. I am thinking this experiment might turn out to be very helpful for
us to design future workshops fully online, including for
developer-wannabees.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GenericMappingTools/2020-unavco-course/issues/1#issuecomment-651154826>,
or unsubscribe

**Comment by PaulWessel** [comment]
Hi @anbj it is probably best after the fact.  Everything will be posted at the UNAVCO short course 2020 site.

**Comment by anbj** [comment]
Great, thanks @PaulWessel
