### ISSUE TITLE
Error while running ./test_1.sh

### ISSUE THREAD

**Issue by ibnsana** [GenericMappingTools/2020-unavco-course#13]
I'm getting the following error while running ./test_1.sh
./test_1.sh: line 3: gmt: command not found
./test_1.sh: line 4: gmt: command not found
./test_1.sh: line 5: gmt: command not found
./test_1.sh: line 6: gmt: command not found

**Comment by PaulWessel** [comment]
So gmt is not installed, of you have installed it but it is not in your system PATH.  Did you follow the instructions to install GMT?

**Comment by ibnsana** [comment]
Yes, I installed it correctly.

**Comment by ibnsana** [comment]
Cloning into '2020-unavco-course'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 80 (delta 19), reused 54 (delta 7), pack-reused 0
Unpacking objects: 100% (80/80), done.

**Comment by JZurutuza** [comment]
ibsana,

What do you get if you type gmt or psxy in the terminal? 

Regards,
J. Zurutuza

**Comment by ibnsana** [comment]
I get this: 
-bash: gmt: command not found

**Comment by JZurutuza** [comment]
Are the gmt executables correctly set in the PATH? Try using find to see where they might be. Seems your installation is not yet done and you need to set some variables.

**Comment by ibnsana** [comment]
How can I do that?

**Comment by joa-quim** [comment]
@ibnsana  What is your operating system and how did you install GMT?

**Comment by ibnsana** [comment]
@joa-quim Operating system: Catalina. I installed GMT using git clone command.

**Comment by joa-quim** [comment]
So you didn't install GMT yet. You only copied its source code. Next you need to compile it, but that's the hardest route. You should had followed the **recommended** way, which is to install the ``.dmg``

**Comment by PaulWessel** [comment]
If the building from source turns out to be a problem we would recommend you just install from the macOS installer which has everything you need.  You can always explore building from source later.

**Comment by ibnsana** [comment]
Thanks. I installed GMT using macOS installer

**Comment by PaulWessel** [comment]
OK, closing this issue - please reopen if any more problems.
