### ISSUE TITLE
test_1.sh runs OK, but BUG found

### ISSUE THREAD

**Issue by JZurutuza** [GenericMappingTools/2020-unavco-course#14]
Dear colleagues,

I have installed gmt 6.1 with no problems and I can execute both verification scripts. However, when I execute script 1, I get the following BUG warning:
insar@linux:~/2020-unavco-course/hw1$ *** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

Best regards,
J. Zurutuza

**Comment by joa-quim** [comment]
Hmm, that is not a GMT error message. Apparently it's from eclipse. See
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492709

**Comment by PaulWessel** [comment]
Perhaps you are double-clicking on the test_1.sh script in a folder window instead of typing the command into a terminal?

**Comment by JZurutuza** [comment]
Dear Joa-quim,

My apologies for this late response.

I'm afraid I do not have eclipse installed... On the other hand, I am executing some of the scripts of the gmtsar course (GMTSAR 6.0+GMT 6.1) and so far they are running fine.

Kind regards,
J. Zurutuza

**Comment by PaulWessel** [comment]
HI @JZurutuza, test_1.sh is only

```
gmt begin test1
	gmt grdimage @earth_relief_20m -R0/40/0/40 -JM15c -I+d -U
	gmt coast -W1p -B
gmt end show
```

See if removing the word "show" lets it run without errors.  if so then I suspect your default tool to open a PDF is causing trouble.  Basically, the "show" ends up calling `xdg-open test1.pdf.`  So you can try to do these steps manually and sort out why that latter command gives those errors.

**Comment by JZurutuza** [comment]
Works!
Now I get no bug error. If I want ot see the map, I just open it.
Thanks for the support!

**Comment by PaulWessel** [comment]
OK, but if you run the original script as is, it gives you an error and does not open the figure?  What does typing xdg-open test1.pdf in the terminal do?

**Comment by JZurutuza** [comment]
1) When I run the original script, the image opens and I get the warning.

2) When I run:
insar@linux:~/2020-unavco-course/hw1$ xdg-open test1.pdf
insar@linux:~/2020-unavco-course/hw1$ *** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

So the bug/error warning seems to come from the xdg-open.

Regards,
J. Zurutuza

**Comment by PaulWessel** [comment]
I am closing this since the GMT part seems to work fine.  Please reopen if there are more problems,
