### ISSUE TITLE
GMTSAR Installation error

### ISSUE THREAD

**Issue by ptimsina-tech** [GenericMappingTools/2020-unavco-course#21]
I tried to install the GMTSAR in Ubuntu 20.04, it works fine up to the configuration level. But, I got an error
![error](https://user-images.githubusercontent.com/62301243/87223629-d7151480-c37e-11ea-911d-9746dd4a27ad.png)
 ([Makefile:44: envi_slc_decode] Error 1 and [Makefile:37: preprocess] Error 2) while doing make and  I am not able to preceed for make install. Please kindly suggest me the way to resolve it.

**Comment by joa-quim** [comment]
This is an error while building GMTSAR. Perhaps post this message there?

**Comment by ptimsina-tech** [comment]
> This is an error while building GMTSAR. Perhaps post this message there?

Thanks. But where you mean to post exactly...I don't get. Sorry

**Comment by PaulWessel** [comment]
Try the github page for GMTSAR: https://github.com/gmtsar/gmtsar
