### ISSUE TITLE
Unspecified country is given same color using coast command

### ISSUE THREAD

**Issue by kstephens13** [GenericMappingTools/2020-unavco-course#35]
I was able to plot up a simple map of South Africa with no issue using the coast command, however the country of Lesotho, which is completely surrounded by South Africa, is also given the same color for the ZA country specification. I've attached the map and the command I used is below:
`gmt coast -RZA -Gwheat -Bg -Wthick -JM15c -N1/thick,black -EZA+ggreen`

**Comment by kstephens13** [comment]
It seems like I cannot upload pngs or PDFs to the issue. Is there perhaps a preferred format? 
Many thanks

**Comment by PaulWessel** [comment]
I think PNGs should work fine - just draw and drop.  Not PDFs though.

**Comment by PaulWessel** [comment]
I suspect this is a "feature" - i.e., donut countries (polygons with holes) may not have been implemented yet.  I will have a look once the workshop is over so leave this issue open please.

**Comment by kstephens13** [comment]
![southafrica_map](https://user-images.githubusercontent.com/68207460/87978998-5ef5cf80-ca9f-11ea-9a49-98ecc27600ad.png)
Ah ha Safari wasn't letting me upload the PNG, but Google Chrome works just fine. 
Sure, I will leave the issue open.

**Comment by leouieda** [comment]
@kstephens13 thank you for finding this and bringing it to our attention! We get so much out of these workshops as well. Paul has already fixed this in GenericMappingTools/dcw-gmt#3 and is already moving to generalize it in GenericMappingTools/dcw-gmt#4 🎉

**Comment by PaulWessel** [comment]
The data have been fixed but using it in GMT will require 6.1.1 and beyond once I have implemented it.
