### ISSUE TITLE
getting ahead on my final project: issues plotting a vector

### ISSUE THREAD

**Issue by ielfking** [GenericMappingTools/2020-unavco-course#37]
For my final project I am wanting to create a map of Iceland showing glacial cover, the locations of a few major volcanoes, and a few vertical velocity vectors (my project is GIA modeling).

I have plotted everything but the velocity vector and I am having trouble doing it with the gmt plot -SV command

here is my error: plot [WARNING]: Mismatch between actual (2) and expected (4) fields near line 1 in file <Standard Input>

code is attached

[iceland_GPS.txt](https://github.com/GenericMappingTools/2020-unavco-course/files/4954529/iceland_GPS.txt)

**Comment by PaulWessel** [comment]
SV takes 4 input columns: lon, lat direction length.  The -SV arg is the size of the vector head only.

**Comment by ielfking** [comment]
how do you format " input columns" do they need commas or slashes and no spaces between? Do they go before or after the -SV arg? It seems pretty foundational but I cant find where it is stated in the documentation.

for instance i need a vector at -17.689, 63.947  with an angle of 0 from north and a length of  2.136cm

**Comment by ielfking** [comment]
I figured out the formatting with the echo statement reading in.

I still need a head on my vector and placing numbers after -SV makes the vector disappear completely

**Comment by ielfking** [comment]
solved it
