### ISSUE TITLE
issue VSC with GIT Bash

### ISSUE THREAD

**Issue by JATarrio** [GenericMappingTools/2020-unavco-course#38]
Hello:
Hello:
The problem that arises is that if I run the scripts in GIT Bash, if they work correctly, but when doing it in real time in VSC with GIT Bash, they don't work.

![capture](https://user-images.githubusercontent.com/59740458/88100791-0db31200-cb6b-11ea-8c0d-24409c7d5fa6.jpg)

Thanks

**Comment by PaulWessel** [comment]
You need to configure VSC to use the bash for git app in the terminal.  See the settings and that little menu taht says bash
