### ISSUE TITLE
Youtube Videos?

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/2020-unavco-course#40]
I see the YouTube videos of the 2019 source (https://www.youtube.com/playlist?list=PLzmugeDoplFMwr1W7dgmwf26p83ie6ZEN) in the UNAVCO YouTube channel (https://www.youtube.com/channel/UC1uOu5gkvJnaiacLj9k3z0w), but I can't find the videos of the 2020 course.

Are the videos available online?

@PaulWessel @joa-quim @leouieda

**Comment by PaulWessel** [comment]
I think so, I have asked Melissa to help.

**Comment by PaulWessel** [comment]
Response:

Hi Paul, 

We have the recordings linked on our website: https://www.unavco.org/education/professional-development/short-courses/2020/geodetic-gmt/geodetic-gmt.html

And they are all in a Google drive file: https://drive.google.com/drive/folders/1MCYdeRiQEhsebVqYZB2xuDGU2Wjp3F_B?usp=sharing


Let me know if that's what you and Dong Dong are looking for?

Thank you,
Melissa M. Weber
Admin. Asst. to ECE (she/her)
UNAVCO, Inc.
ph: 303-381-7562
fax: 303-381-7501
weber@unavco.org
UNAVCO is closely monitoring the COVID-19 pandemic. You can follow UNAVCO alerts at: https://alerts.unavco.org/

**Comment by seisman** [comment]
Yes, I can find the videos in the Google Drive folder. I thought all videos were uploaded to YouTube for broad audiences.

**Comment by leouieda** [comment]
Could we upload those to our channel?

**Comment by seisman** [comment]
> Could we upload those to our channel?

Even better!

**Comment by PaulWessel** [comment]
UNAVCO is looking into how they want to do all of this, so we can just wait.  I mentioned we also have a YouTUbe channel if they would prefer that.  I think we will let them make a decision and then we adapt to that.  They do want to do something uniform across the years.

**Comment by seisman** [comment]
Great! Now the videos are available at https://www.youtube.com/playlist?list=PLzmugeDoplFPq6k7u1ebNbiBzqFA-OwXF
